[versions]
agp = "8.6.0"
cardview = "1.0.0"
firebaseBom = "33.13.0"
firebaseMessaging = "24.1.1"
googleApiClient = "1.33.0"
googleAuthLibraryOauth2Http = "1.6.0"
googleOauthClient = "1.33.0"
googleServices = "4.4.2"
gradle = "8.7.3"
jtds = "1.3.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
mariadbJavaClient = "1.8.0"
material = "1.12.0"
constraintlayout = "2.2.0"
lifecycleLivedataKtx = "2.8.7"
lifecycleViewmodelKtx = "2.8.7"
materialCalendarview = "2.0.1"
materialCalendarviewVersion = "2.0.0"
materialVersion = "1.6.0"
navigationFragment = "2.8.3"
navigationUi = "2.8.3"
legacySupportV4 = "1.0.0"
onesignal = "[4.0.0,4.0.0)"
poiOoxml = "5.2.3"
recyclerview = "1.3.0"
recyclerviewVersion = "1.2.1"

[libraries]
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-inappmessaging-display = { module = "com.google.firebase:firebase-inappmessaging-display" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
google-api-client = { module = "com.google.api-client:google-api-client", version.ref = "googleApiClient" }
google-auth-library-oauth2-http = { module = "com.google.auth:google-auth-library-oauth2-http", version.ref = "googleAuthLibraryOauth2Http" }
google-oauth-client = { module = "com.google.oauth-client:google-oauth-client", version.ref = "googleOauthClient" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
jtds = { module = "net.sourceforge.jtds:jtds", version.ref = "jtds" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
mariadb-java-client = { module = "org.mariadb.jdbc:mariadb-java-client", version.ref = "mariadbJavaClient" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
material-calendarview = { module = "com.prolificinteractive:material-calendarview", version.ref = "materialCalendarview" }
material-v160 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }
onesignal = { module = "com.onesignal:OneSignal", version.ref = "onesignal" }
poi = { module = "org.apache.poi:poi", version.ref = "poiOoxml" }
poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "poiOoxml" }
prolificinteractive-material-calendarview = { module = "com.github.prolificinteractive:material-calendarview", version.ref = "materialCalendarviewVersion" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
recyclerview-v121 = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerviewVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
